<a href="https://colab.research.google.com/github/Habir55/Deep-Learning-with-Python-/blob/main/Tensor_Exercise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# Tensor can have different dimensions. Let us create one-dimensional array/tensor/vector. 

x = torch.empty(3)
x

tensor([6.3954e-35, 0.0000e+00, 3.3631e-44])

In [3]:
# Two-dimensional tensor: 
y = torch.empty(2, 3)
y

tensor([[6.3954e-35, 0.0000e+00, 3.3631e-44],
        [2.0000e+00, 0.0000e+00, 1.8750e+00]])

In [4]:
# It can be also 3-D: 
z = torch.empty(2, 3 ,4)
z

tensor([[[6.3037e-35, 0.0000e+00, 7.0065e-44, 7.0065e-44],
         [6.3058e-44, 6.7262e-44, 7.4269e-44, 6.3058e-44],
         [7.0065e-44, 7.8473e-44, 1.1771e-43, 6.8664e-44]],

        [[6.8664e-44, 8.1275e-44, 7.2868e-44, 7.0065e-44],
         [8.1275e-44, 7.1466e-44, 7.1466e-44, 6.4460e-44],
         [7.1466e-44, 7.1466e-44, 7.9874e-44, 7.2868e-44]]])

In [5]:
# It is also possible to creat a matrix including only ones or zeros. we can aslo specify the data types. 

x1 = torch.ones(2, 3, dtype=torch.float64)
x2 = torch.zeros(4, 5)
x1, x2

(tensor([[1., 1., 1.],
         [1., 1., 1.]], dtype=torch.float64), tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]))

In [6]:
x1.dtype

torch.float64

In [7]:
x2.size()

torch.Size([4, 5])

In [8]:
# Let us try, with list inside the tensor: 
x3 = torch.tensor([2.5, 0.1])
x3

tensor([2.5000, 0.1000])

In [9]:
# let us try to add two tensors which have the same dimensions.
a = torch.rand(2,2)
b = torch.rand(2,2)
a, b

(tensor([[0.7173, 0.5111],
         [0.4633, 0.0569]]), tensor([[0.9075, 0.8981],
         [0.1953, 0.1522]]))

In [10]:
c = a + b
c

tensor([[1.6248, 1.4092],
        [0.6585, 0.2091]])

In [11]:
# this also does the same work 
c = torch.add(a,b)
c

tensor([[1.6248, 1.4092],
        [0.6585, 0.2091]])

In [12]:
# if want to add all of the elements of 'a' to 'b', we can do the following and it will be an inplace operation and it will modifey the variable applied on:
b.add_(a)

tensor([[1.6248, 1.4092],
        [0.6585, 0.2091]])

In [13]:
# let us see how to do a subtraction in pytorch: 
a, b 

# these two methods, do the same thing: 
e = a - b
e

tensor([[-0.9075, -0.8981],
        [-0.1953, -0.1522]])

In [14]:
e = torch.sub(a,b)
e

tensor([[-0.9075, -0.8981],
        [-0.1953, -0.1522]])

In [15]:
# we can also multiply the tensors: 
f = a * b
f

tensor([[1.1654, 0.7202],
        [0.3051, 0.0119]])

In [16]:
f = torch.mul(a,b)
f

tensor([[1.1654, 0.7202],
        [0.3051, 0.0119]])

In [17]:
# we can do everything in place by saying:
a.mul_(b) # this will modify a

tensor([[1.1654, 0.7202],
        [0.3051, 0.0119]])

In [18]:
a # as we can see, values in a are different from the original a tensor now. 

tensor([[1.1654, 0.7202],
        [0.3051, 0.0119]])

In [19]:
# Slicing: 
g = torch.rand(5,3)
g

tensor([[0.7994, 0.9381, 0.1368],
        [0.9665, 0.7998, 0.9519],
        [0.0065, 0.3425, 0.5511],
        [0.6129, 0.0372, 0.2028],
        [0.5103, 0.7803, 0.7402]])

In [20]:
# we wanna have the first column of every row: 
g[:, 0]

tensor([0.7994, 0.9665, 0.0065, 0.6129, 0.5103])

In [21]:
# if we wanna have, every elements of third row:
g[2]

tensor([0.0065, 0.3425, 0.5511])

In [22]:
# if I want to get, one specific value within the list: 
# this is the last element, we can also get it by saying invoking [-1,-1]
g[4,2], g[-1, -1] # if we type only g[-1], Python will give us every elements of last row. 

(tensor(0.7402), tensor(0.7402))

In [23]:
# if we slice only one element of the tenor and wonder its actual value, we can use item() function: 
g[2,2].item() # in tensors, it only shows 0.0965

0.5510887503623962

In [24]:
# Now, let us see how to reshape a tensor: 

h = torch.rand(4,4)
h

tensor([[0.6515, 0.6955, 0.2727, 0.4582],
        [0.5520, 0.0824, 0.4738, 0.5467],
        [0.4199, 0.3467, 0.5222, 0.8081],
        [0.4319, 0.6393, 0.3870, 0.9155]])

In [25]:
# if we wanna see it, in only one line/vector we can use view() function: 
k = h.view(16)
k

tensor([0.6515, 0.6955, 0.2727, 0.4582, 0.5520, 0.0824, 0.4738, 0.5467, 0.4199,
        0.3467, 0.5222, 0.8081, 0.4319, 0.6393, 0.3870, 0.9155])

In [26]:
# if we do not want to put it into one dimention, we can basically type view(-1, any number), then python will anaylze it and give us the reshaped tensor:
l = h.view(-1, 8)
l # as we can see, it is 2x8 now. 
l, l.size()

(tensor([[0.6515, 0.6955, 0.2727, 0.4582, 0.5520, 0.0824, 0.4738, 0.5467],
         [0.4199, 0.3467, 0.5222, 0.8081, 0.4319, 0.6393, 0.3870, 0.9155]]),
 torch.Size([2, 8]))

In [27]:
# Converging from Numpy to Tensor and vice verca: 
import numpy as np 

In [28]:
m = torch.ones(5)
m # it is a tensor now!

tensor([1., 1., 1., 1., 1.])

In [29]:
n = m.numpy()
n, type(n) 

# as we can see, it changed to numpy ndarray now!

(array([1., 1., 1., 1., 1.], dtype=float32), numpy.ndarray)

In [30]:
# Vice versa:
c = np.ones(6)
c, type(c)

(array([1., 1., 1., 1., 1., 1.]), numpy.ndarray)

In [31]:
v = torch.from_numpy(c) # we can specify the data types if it is necessary
v, type(v)

(tensor([1., 1., 1., 1., 1., 1.], dtype=torch.float64), torch.Tensor)

In [32]:
# We have to be careful about one thing that, since both numpy and tensor is using the same memory location, if we modify one of them the other will 
# also be modified automatically. 
c += 1 # every time I run this, it will add 1 
c 

array([2., 2., 2., 2., 2., 2.])

In [33]:
v # as it is clear, the tensor got also modified!

tensor([2., 2., 2., 2., 2., 2.], dtype=torch.float64)

In [34]:
torch.cuda.is_available()

True

In [45]:
# Running the codes on GPU is much faster!
# If wanna change GPU to CPU or vice versa, we cab us .cuda() and .cpu() functions , for example: 
torch.cuda.is_available() # now it is one GPU. 

j = torch.ones(9)
t = j.cpu()
print("t device is:", t.device)

t device is: cpu


In [48]:
# As vice versa: 
t1 = j.cuda()
print("t1 device is:", t1.device)

t1 device is: cuda:0


In [ ]:
## DONE ## 