## Practice Exercises of Chapter_2 : PyTorch Tensors



In [110]:
import torch

• Create variable a = list(range(9))

In [111]:
a = torch.arange(9)
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

--> Pick a mathematical operation like cosine or square root. Can you find a corresponding function in the PyTorch library?

In [112]:
a.sin(), a.sqrt(), a.square()

(tensor([ 0.0000,  0.8415,  0.9093,  0.1411, -0.7568, -0.9589, -0.2794,  0.6570,
          0.9894]),
 tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284]),
 tensor([ 0,  1,  4,  9, 16, 25, 36, 49, 64]))

--> Apply the function element-wise to a. Why does it return an error?

In [113]:
a[5].square(), a[3:7].square()

(tensor(25), tensor([ 9, 16, 25, 36]))

--> Did you perform the operation on GPU or CPU? How can you find that out?

In [114]:
torch.cuda.is_available

<function torch.cuda.is_available>

In [115]:
if torch.cuda.is_available:
  print("You can use GPUs!")
else:
  print("You cannot use GPUs!")

You can use GPUs!


--> Can you change your code to execute on GPU and CPU?

In [116]:
# to work on GPU we use .cuda() command, and to work in CPU we use .cpu() command! 
a1 = a.cpu()

In [117]:
print("a1 device is :", a1.device)

a1 device is : cpu


In [118]:
# let us turn back to GPU

a2 = a1.cuda()

In [119]:
# let us check it now:

print("a2 device is :", a2.device)

a2 device is : cuda:0


--> what is the datatype of your result? 

In [120]:
a.dtype

torch.int64

In [121]:
# let me change the data type with .to() command: 
a3 = a.to(torch.float64)
a3
print("Data type of a3 is:", a3.dtype)

Data type of a3 is: torch.float64


In [122]:
# let me turn the data type back to the torch.int64:
a4 = a3.to(torch.int64)
print("Data type of a4 is :", a4.dtype)

Data type of a4 is : torch.int64


--> What is the shape of the result and total number of elements in it? 

In [123]:
a4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [124]:
a4.shape

torch.Size([9])

In [125]:
# to learn the total elements of a tensor we can use .numel() function: 
a4.numel()

# as we can see, it gives the number of the elements inside the tensor!

9

--> Reshape the result into 3x2 matrix. Why does it return an error? 
--> Reshape the result into 3x3 matrix. 

In [126]:
# A = a4.reshape(3,2) --> because: the shape '[3, 2]' is invalid for input of size 9

A = a4.reshape(3,3)
A

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

--> Can you transpose the matrix using reshape? If not, use PyTorch functions to transpose the result matrix.

In [127]:
# it is not possible to transpose a matrix with reshape() function. Because it takes elements in row-major order. So basically, we can use .t() function to transpose a matrix: 
A.t() # that is it!

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

--> Create a tensor b of shape (2,1) with all elements 2. 

In [128]:
b = torch.tensor([2,2])
b = b.reshape(2,1)
b

tensor([[2],
        [2]])

--> Can you add b to your previous result? Why does it return an error? 

In [129]:
# A + b. Due to the difference in size of the matrices, we cannot add them to each other.

--> Update b to shape (3,1) with all elements 10. 

In [130]:
b = torch.tensor([10,10,10])
b = b.reshape(3,1)
b, A

(tensor([[10],
         [10],
         [10]]), tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]))

--> Add b to your result. Do you understand the output? 

In [131]:
B = A + b
B # A was (3x3) size and b is (3x1) size. I think, A is added to every column of b one by one!

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

--> Update the elements in the second row of your result to 100.

In [132]:
B[1] = 100
B

tensor([[ 10,  11,  12],
        [100, 100, 100],
        [ 16,  17,  18]])

--> Concatenate the results with itself to form a larger tensor of shape (3,6)

In [133]:
torch.cat((B,B), dim=0) # now it is 6,3 so let me try dim=1

tensor([[ 10,  11,  12],
        [100, 100, 100],
        [ 16,  17,  18],
        [ 10,  11,  12],
        [100, 100, 100],
        [ 16,  17,  18]])

In [134]:
B1= torch.cat((B,B), dim=1) 
B1 # It is achieved!

tensor([[ 10,  11,  12,  10,  11,  12],
        [100, 100, 100, 100, 100, 100],
        [ 16,  17,  18,  16,  17,  18]])

--> Reduce the row dimension of the result by summing up row elements.

In [135]:
B1_sum_axis0 = B1.sum(axis=0) # axis = dimenstion, which means that as row comes first.
#Due to the fact that Python is zero-indexed, axis=0 referes to row dimenstion and axis=1 refers to column dimension.
B1_sum_axis0, B1_sum_axis0.shape

(tensor([126, 128, 130, 126, 128, 130]), torch.Size([6]))

In [136]:
B1_sum_axis1 = B1.sum(axis=1)
B1_sum_axis1, B1_sum_axis1.shape

(tensor([ 66, 600, 102]), torch.Size([3]))

--> Take the dot product of the result with itself! 

Quick recall: Dot product is a sum over the products of the elements at the same position in the two vectors.

In [137]:
B2 = B1_sum_axis0
B3 = torch.dot(B2,B2)
B3

tensor(98320)

In [138]:
## Let me try to find the same result with another way: 
# I will firstly take the square values of B1_sum_axis0 and then sum all the value!

torch.square(B2).sum() # it worked out! 

tensor(98320)

--> Convert the resulting tensor to NumPy ndarray. Why does it return an error?

In [139]:
type(B3)

torch.Tensor

In [141]:
C = B3.numpy()
type(C)

numpy.ndarray

--> Convert it back to PyTorch Tensor.

In [143]:
D = torch.tensor(C)
type(D)

torch.Tensor

### Exercise of Chapter_2 is finished here! 